version: "3"

services:
  web:
    build: .
    ports:
      - 50051:50051
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
